on: push
jobs:
  build:
    uses: ashep/ci/.github/workflows/js-build.yaml@v1
    with:
      registry_user: ${{ vars.REGISTRY_USER }}
    secrets:
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}

